<!-- Specify the report's official name, goal & description. -->
# REDCap Demo
**Report Goal**:  Results of Demo Psychopathic Tendencies Survey
**Report Description**: Results of this survey are not real.  This was only a demo.


```{r, echo=FALSE, message=F} 
#Set the chunks' working directory to the repository's base directory; this assumes the report is nested inside of two directories.
knitr::opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -espeically one that uses file paths.
```
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# cat("Working directory: ", getwd())
require(knitr)

#To help knitr parse these arguments correctly, put comments at the end of call, not after each line. 
opts_chunk$set(
  results='show', 
  comment = NA, 
  tidy = FALSE,
  fig.width = 6.5, 
  fig.height = 4, 
  fig.path = 'figure_raw/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.

read_chunk("./analyses/psychopath_demo/demo_survey.R")  #This allows knitr to call chunks tagged in the underlying *.R file.
```

<!-- Load any source files containing functions. --> 
```{r load_sources, echo=echoChunks, message=FALSE}
```

<!-- Load the packages.  Suppress the output when loading packages. --> 
```{r load_packages, echo=echoChunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=FALSE, message=FALSE}
PrintTable <- function( dsTable ) {
  print(xtable(dsTable), type="html")
}
```

<!-- Load the datasets.   -->
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak_data, echo=echoChunks, results='show', message=FALSE}
```

### Gender of Demo Participants
```{r gender, echo=F, results='hide'}
```

### Self-report of Psychopathic Behaviors
```{r psychopath_characteristics, echo=F, results='hide'}
```

### Self-report of Juvenile Delinquency
```{r juvenile_delinquency, echo=F, results='hide'}
```

### Self-report on Realistic Long-Term Goals
```{r long_term_goals, echo=F, results='hide'}
```

### Self-report on Realistic Long-Term Goals
```{r psychopathic_score_and_lack_of_realistic_goals, echo=F, results='hide'}
```
