<!-- Specify the report's official name, goal & description. -->
# REDCap Demo
**Report Goal**:  Results of Demo Psychopathic Tendencies Survey
**Report Description**: Results of this survey are not real.  This was only a demo.


```{r, echo=FALSE, message=F} 
#Set the chunks' working directory to the repository's base directory; this assumes the report is nested inside of two directories.
opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -espeically one that uses file paths.
```
<!-- Point knitr to the underlying code file so it knows where to look for the chunks. -->
```{r, echo=FALSE, message=FALSE}

options(width=180)
opts_chunk$set(comment="", warning=FALSE, echo=TRUE, tidy=FALSE, size="small")
library(xtable)
pathSourceCode <- "./Demo/PsychopathDemo/DemoSurvey.R"

#This allows knitr to call chunks tagged in the underlying PrototypeCode.R file.
read_chunk(pathSourceCode) 
```

<!-- Load the packages.  Suppress the output when loading packages. --> 
```{r LoadPackages, echo=FALSE, message=FALSE}
```

<!-- Load any Global Functions declared in the R file.  Suppress the output. --> 
```{r DeclareGlobalFunctions, echo=FALSE, message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=FALSE, message=FALSE}
PrintTable <- function( dsTable ) {
  print(xtable(dsTable), type="html")
}
```

<!-- Load the dataset.  Suppress the output. -->
```{r LoadDS, echo=F, results='hide'}
```

### Gender of Demo Participants
```{r Gender, echo=F, results='hide'}
```

### Self-report of Psychopathic Behaviors
```{r PsychopathCharacteristics, echo=F, results='hide'}
```

### Self-report of Juvenile Delinquency
```{r JuvenileDelinquency, echo=F, results='hide'}
```

### Self-report on Realistic Long-Term Goals
```{r LongTermGoals, echo=F, results='hide'}
```

### Self-report on Realistic Long-Term Goals
```{r PsychopathicScoreAndLackOfRealisticGoals, echo=F, results='hide'}
```
